ViddiCurrent/interview/urls.py
from django.urls import include, path

from .views import interview, interviewee, interviewer
from .views import *
urlpatterns = [
    path('home/', interview.home, name='home'),
    path('interviewer/', include(([
         path('', interviewer.manage_dashboard, name='dashboard'),

         path('users/', interviewer.UserManagementListView.as_view(),
              name='user_management_list'),
         path('users/add/', interviewer.InterviewerSignUpView.as_view(),
              name='user_management_add'),
         path('users/<int:pk>/', interviewer.InterviewerUpdateView.as_view(),
              name='user_management_edit'),
         path('users/<int:pk>/delete/', interviewer.InterviewerDeleteView.as_view(),
              name='user_management_delete'),

         path('company/', interviewer.CompanyListView.as_view(), name='company_list'),
         path('company/add/', interviewer.CompanyCreateView.as_view(),
              name='company_add'),
         path('company/email/<int:pk>',
              interviewer.CompanyEmailView.as_view(), name='company_email'),
         path('company/<int:pk>/edit',
              interviewer.CompanyUpdateView.as_view(), name='company_edit'),
         path('company/<int:pk>/delete/',
              interviewer.CompanyDeleteView.as_view(), name='company_delete'),

         path('questions/', interviewer.QuestionListView.as_view(),
              name='questions_list'),
         path('questions/add/', interviewer.QuestionCreateView.as_view(),
              name='question_add'),
         path('questions/<int:pk>/',
              interviewer.QuestionUpdateView.as_view(), name='question_edit'),
         path('questions/<int:pk>/delete/',
              interviewer.QuestionDeleteView.as_view(), name='question_delete'),

         path('vacancies/', interviewer.VacancyListView.as_view(),
              name='vacancies_list'),
         path('vacancies/add/', interviewer.VacancyCreateView.as_view(),
              name='vacancy_add'),
         path('vacancies/<int:pk>/',
              interviewer.VacancyUpdateView.as_view(), name='vacancy_edit'),
         path('vacancies/<int:pk>/delete/',
              interviewer.VacancyDeleteView.as_view(), name='vacancy_delete'),

         path('interviews/', interviewer.InterviewListView.as_view(),
              name='interviews_list'),
         path('interviews/add/', interviewer.InterviewCreateView.as_view(),
              name='interview_add'),
         path('interviews/<int:pk>/',
              interviewer.InterviewUpdateView.as_view(), name='interview_edit'),
         path('interviews/<int:pk>/delete/',
              interviewer.InterviewDeleteView.as_view(), name='interview_delete'),
         path('interviews/<int:pk>/candidate/add/',
              interviewer.interviewee_create, name='interviewee_add'),
         path('interviews/<int:pk>/candidates/all/', interviewer.InterviewCandidateListView.as_view(),
              name='interview_candidates_list'),
         path('interviews/<int:pk>/candidates/complete/', interviewer.InterviewCompleteCandidateListView.as_view(),
              name='interview_complete_candidates_list'),
         path('interviews/<int:interview_pk>/candidate/<int:candidate_pk>/', interviewer.interviewee_review,
              name='interviewee_review'),

         path('candidates/', interviewer.CandidateListView.as_view(),
              name='candidates_list'),
         path('candidates/<int:pk>/delete/',
              interviewer.CandidateDeleteView.as_view(), name='candidate_delete'),

         path('settings/', interviewer.manage_settings, name='settings'), ], 'interview'), namespace='interviewer')),

    path('interviewee/', include(([

        path('', interviewee.CandidateInterviewListView.as_view(), name='dashboard'),
        path('interview/<int:pk>/', interviewee.interviewee_interview,
             name='interviewee_attempt'),
        path('interview/practice/', interviewee.interview_practice, name='interview_practice'), ], 'interview'), namespace='interviewee')),
]

ViddiCurrent/turborecruit/urls.py
from django.urls import path, include
from interview.views import interview, messages
from interview.forms import AdminAuthenticationForm, MyPasswordChangeForm
from django.conf.urls import handler404, handler500
from django.contrib.auth import views
from django.urls import reverse_lazy
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', interview.index, name="index"),
    path('admin/', interview.AdminLoginView.as_view(), name='login'),
    path('user/', interview.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('', include('interview.urls')),
    # path('index/', interview.HomePageView.as_view(), name='index'),
    path('accounts/signup/admin/', interview.AdminSignUpView.as_view(), name='admin_signup'),
    # path('accounts/edit/admin/<int:pk>/', interview.AdminUpdateView.as_view(), name='admin_edit'),
] + [
    path('password_change/', views.PasswordChangeView.as_view(
        success_url=reverse_lazy('login'),
        form_class=MyPasswordChangeForm),
        name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    # Work pending : Forgot Password flow
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = messages.error_404
handler500 = messages.error_500

ViddiCurrent/interview/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe
import datetime
from django import forms


class User(AbstractUser):
    USER_TYPE_CHOICES = (
        (1, 'Super Admin'),
        (2, 'Company Admin'),
        (3, 'Company Reviewer'),
        (10, 'Student'),
    )
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES)
    company_name = models.CharField(max_length=100, default="")

    def __str__(self):
        return self.email

    def get_html_badge(self):
        company_name = escape(self.company_name)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (
            company_name)
        return mark_safe(html)

class Company(models.Model):
    name = models.CharField('Company', max_length=30)
    img = models.ImageField(upload_to='')
    about = models.TextField('About', blank=True)
    email = models.CharField(max_length=100, null=True)
    email_template = models.TextField('Email Template', blank=True)
    address = models.TextField('Address', blank=True)
    color = models.CharField(max_length=7, default='#007bff')

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (
            color, name)
        return mark_safe(html)


class Interviewer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True, related_name='working_organization')
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='working_organization')

    def __str__(self):
        return self.user.username


class Question(models.Model):
    question_owner = models.ForeignKey(
        User, on_delete=models.SET(1), related_name='question_owner')
    text = models.CharField('Question', max_length=255)
    time = models.PositiveIntegerField('Time', default=30)
    owner_company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='owner_company')

    def __str__(self):
        return self.text


class Vacancy(models.Model):

    STATUS_TYPE_CHOICES = (
        ('Active', 'Active'),
        ('Pause', 'Pause'),
    )

    vacancy_owner = models.ForeignKey(
        User, on_delete=models.SET(1), related_name='vacancy_owner')
    position = models.CharField('Position', max_length=255)
    description = models.TextField(blank=True, default='')
    count = models.PositiveIntegerField('Vacancy Count', default=1)
    status = models.CharField(choices=STATUS_TYPE_CHOICES, max_length=10)
    # status = models.PositiveSmallIntegerField(choices=STATUS_TYPE_CHOICES)
    start_date = models.DateField(
        default=datetime.date.today().strftime("%d/%m/%Y"))
    end_date = models.DateField(
        default=datetime.date.today().strftime("%d/%m/%Y"))
    organisation = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='owner_organisation')

    def __str__(self):
        return self.position


class Interview(models.Model):
    interview_owner = models.ForeignKey(
        Interviewer, on_delete=models.SET(1), related_name='interview_owner')
    position_name = models.OneToOneField(
        Vacancy, on_delete=models.CASCADE, related_name='position_name')
    interview_organisation = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='interview_organisation')
    # questions = models.ManyToManyField(Question, related_name='questions')
    questions = models.ManyToManyField(Question, through='InterviewQuestions')

    def __str__(self):
        return self.position_name.position


class InterviewQuestions(models.Model):
    taken_interviews = models.ForeignKey(
        Interview, on_delete=models.CASCADE, related_name='question_interview')
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name='question_link')
    index = models.PositiveIntegerField('Question Index', default=1)


class Interviewee(models.Model):
    user_for_interview = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,
                                              related_name='user_for_interview')
    interviews = models.ManyToManyField(Interview, through='TakenInterview')
    phone = models.CharField(max_length=30, blank=True)
    name = models.CharField(max_length=30, default="", blank=True)

    def __str__(self):
        return self.user_for_interview.username


class Review(models.Model):
    REVIEW_STATUS_TYPE_CHOICES = (
        (0, 'Not reviewed'),
        (1, 'Shortlisted'),
        (2, 'Rejected'),
    )
    ONE_TO_FIVE_RATING_CHOICES = (
        (0, '0'),
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    reviewer = models.ForeignKey(
        Interviewer, on_delete=models.SET(1), related_name='reviewer_owner')
    review_status = models.PositiveSmallIntegerField(
        choices=REVIEW_STATUS_TYPE_CHOICES, default=0)
    rating = models.PositiveSmallIntegerField(
        choices=ONE_TO_FIVE_RATING_CHOICES, default=0)
    comment = models.CharField(max_length=255)
    review_create_date = models.DateTimeField(auto_now_add=True)


class Answer(models.Model):
    candidate = models.ForeignKey(
        Interviewee, on_delete=models.CASCADE, related_name='candidate_answer')
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name='candidate_question')
    video_id = models.CharField(max_length=255, default='')
    video_name = models.CharField(max_length=1024, default='')
    location = models.CharField(max_length=1024, default='')
    text = models.CharField('Answer', max_length=255, default='')
    index = models.PositiveIntegerField('Question Index', default=1)

    def __str__(self):
        return self.text


class TakenInterview(models.Model):
    INTERVIEW_STATUS_TYPE_CHOICES = (
        (1, 'Pending'),
        (2, 'Active'),
        (3, 'Complete'),
        (4, 'Canceled'),
        (5, 'Expired'),
        (101, 'Practice Pending'),
        (102, 'Practice Active'),
        (103, 'Practice Complete'),
    )

    taken_interviews = models.ForeignKey(
        Interview, on_delete=models.CASCADE, related_name='taken_interviews')
    candidate = models.ForeignKey(
        Interviewee, on_delete=models.CASCADE, related_name='candidate')
    status = models.PositiveSmallIntegerField(
        choices=INTERVIEW_STATUS_TYPE_CHOICES)
    review = models.ManyToManyField(Review, related_name='review')
    answers = models.ManyToManyField(Answer, related_name='answer')
    interview_create_date = models.DateTimeField(auto_now_add=True)
    interview_attempt_date = models.DateTimeField(blank=True, null=True)
    shared_to_users = models.ManyToManyField(
        Interviewer, related_name='shared_to_users')


class PracticeInterview(models.Model):
    INTERVIEW_STATUS_TYPE_CHOICES = (
        (101, 'Practice Pending'),
        (102, 'Practice Active'),
        (103, 'Practice Complete'),
    )

    taken_interviews = models.ForeignKey(
        Interview, on_delete=models.CASCADE, related_name='practice_interviews')
    candidate = models.ForeignKey(
        Interviewee, on_delete=models.CASCADE, related_name='practice_candidate')
    status = models.PositiveSmallIntegerField(
        choices=INTERVIEW_STATUS_TYPE_CHOICES)
    answers = models.ManyToManyField(Answer, related_name='practice_answer')
    interview_create_date = models.DateTimeField(auto_now_add=True)
    interview_attempt_date = models.DateTimeField(blank=True, null=True)


class Settings(models.Model):
    VIDEO_TYPE_CHOICES = (
        (1, 'Add Pipe'),
    )
    setting_updated_by = models.ForeignKey(
        Interviewer, on_delete=models.SET(1), related_name='setting_updated_by')
    setting_updated_date = models.DateTimeField(auto_now_add=True)
    organisation = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='setting_organisation')
    welcome_message = models.TextField(
        blank=True, default='Welcome to Video Interview')
    interview_instructions = models.TextField(
        blank=True, default='Please complete questions within the time Limit.')
    thank_you_message = models.TextField(blank=True,
                                         default='Thank you for completing to video interview process. '
                                                 'We will be in touch shortly.')
    status = models.PositiveSmallIntegerField(
        choices=VIDEO_TYPE_CHOICES, default=1)
    practice_interview = models.ForeignKey(Interview, null=True, on_delete=models.SET(1),
                                           related_name='setting_practice_question')

ViddiCurrent/interview/views/interview.py
from django.shortcuts import redirect, render
from django.views.generic import CreateView, TemplateView, UpdateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login, logout
from ..forms import (UserAuthenticationForm, )

from ..forms import AdminSignUpForm, AdminAuthenticationForm
from ..models import User
from turborecruit.settings import DEBUG


class HomePageView(TemplateView):
    template_name = 'index.html'


# Redirect user to respect dashboard based on User Type
def home(request):
    if request.user.is_authenticated:
        if request.user.user_type < 10:
            return redirect('interviewer:dashboard')
        else:
            return redirect('interviewee:dashboard')
    return render(request, 'login')


# Redirect User from index to user portal by default
def index(request):
    return redirect('user_login')


class AdminLoginView(LoginView):
    """
    Custom admin login view.
    """
    form_class = AdminAuthenticationForm
    template_name = 'registration/admin_login.html'
    redirect_authenticated_user = True

    def form_valid(self, form):
        if not form.get_user().user_type < 10:
            logout(self.request)
            return redirect('user_login')
        return super(AdminLoginView, self).form_valid(form)


class UserLoginView(LoginView):
    """
    Custom user login view.
    """
    form_class = UserAuthenticationForm
    template_name = 'registration/user_login.html'
    redirect_authenticated_user = True


class AdminSignUpView(CreateView):
    model = User
    form_class = AdminSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'admin'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('index')


class AdminUpdateView(UpdateView):
    model = User
    form_class = AdminSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'admin'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('index')

ViddiCurrent/interview/views/messages.py
from django.shortcuts import render


def error_404(request, exception):
    data = {}
    return render(request, '404.html', data)


def error_500(request):
    data = {}
    return render(request, '500.html', data)

ViddiCurrent/interview/templates/authbase.html
{% extends "admin_base.html" %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<aside id="leftsidebar" class="sidebar">
   <div class="Logo_Sidebar">
      {% if user.user_type > 4 %}
      <a><img src="{{ company.img.url }}" style="max-width: 100px;"></a>
      {% elif user.user_type < 2  %}
      <a><img src="{% static 'img/6d792b0b-d307-11e9-956c-42010a8a0ff2' %}" alt="" class="O-Click menu-open"></a>
      <a><img src="{% static 'img/0.png' %}" alt="" class="Second_Image_O menu-open"></a>
      <div class="Arrow A-Open"><span class="Arrow_Manage"></span></div>
      {% endif %}
   </div>
   <div class="toggle_bar">
      <i class="fa fa-bars" aria-hidden="true"></i>
   </div>
   <!-- Menu -->
   <div class="menu">
      <ul class="list menu-open">
         {% if user.user_type < 10 %}
         <li class="">
            <a href="{% url 'interviewer:dashboard' %}">
               <span>
                  <div class="ImageSet" style="width: 30px;">
                     <img src="{% static 'img/583076b2-cf13-11e9-aa34-42010a8a0fed' %}" class="Das">
                  </div>
                  <b>Dashboard</b>
               </span>
            </a>
         </li>
         {% endif %}
         {% if user.user_type < 3 %}
         <li class="active">
            <a href="{% url 'interviewer:user_management_list' %}">
               <span>
                  <div class="ImageSet" style="width: 30px;">
                     <img src="{% static 'img/bccbc5c9-cf13-11e9-aa34-42010a8a0fed' %} ">
                  </div>
                  <b>Users</b>
               </span>
            </a>
         </li>
         {% endif %}
         {% if user.user_type < 3 %}
         <li class="active">
            <a href="{% url 'interviewer:company_list' %}">
               <span>
                  <div class="ImageSet" style="width: 30px;">
                     <img src="{% static 'img/building-16.png' %} " class="Das Libr">
                  </div>
                  <b>Companies</b>
               </span>
            </a>
         </li>
         {% endif %}
         {% if user.user_type < 10 %}
         <li class="">
            <a href="{% url 'interviewer:questions_list' %}">
               <span>
                  <div class="ImageSet" style="width: 30px;">
                     <img src="{% static 'img/books-stack-of-three.png' %} " class="Das Libr">
                  </div>
                  <b>Question Library</b>
               </span>
            </a>
         </li>
         {% endif %}
         {% if user.user_type < 10 %}
         <li class="">
            <a href="{% url 'interviewer:vacancies_list' %}">
               <span>
                  <div class="ImageSet" style="width: 30px;">
                     <img src="{% static 'img/c25f6256-cf13-11e9-aa34-42010a8a0fed' %} " class="Das">
                  </div>
                  <b>Vacancies</b>
               </span>
            </a>
         </li>
         {% endif %}
         {% if user.user_type < 10 %}
         <li class="">
            <a href="{% url 'interviewer:interviews_list' %}">
               <span>
                  <div class="ImageSet" style="width: 30px;">
                     <img src="{% static 'img/5d576e72-cf13-11e9-aa34-42010a8a0fed' %} " class="Das">
                  </div>
                  <b>Interviews</b>
               </span>
            </a>
         </li>
         {% endif %}
         {% if user.user_type < 10 %}
         <li class="">
            <a href="{% url 'interviewer:candidates_list' %}">
               <span>
                  <div class="ImageSet" style="width: 30px;">
                     <img src="{% static 'img/4bbb38fa-cf13-11e9-aa34-42010a8a0fed' %} " class="Das">
                  </div>
                  <b>Candidate List</b>
               </span>
            </a>
         </li>
         {% endif %}
         {% if user.user_type < 2 %}
         <li class="">
            <a href="{% url 'interviewer:settings' %}">
               <span>
                  <div class="ImageSet" style="width: 30px;">
                     <img src="{% static 'img/b08d9ea8-cf13-11e9-aa34-42010a8a0fed' %} " class="Das">
                  </div>
                  <b>Settings</b>
               </span>
            </a>
         </li>
         {% endif %}
      </ul>
   </div>
</aside>
<div class="container-fluid">
</div>


{% block interviewercontent %}

{% endblock %}
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endblock %}

ViddiCurrent/interview/templates/userbase.html
{% extends "user_base.html" %}
{% load static %}
{% block content %}
  {% if user.is_authenticated %}
    <header>
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <nav class="navbar navbar-expand-lg navbar-light fixed-top">
              <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
              <span class=""><i class="fas fa-bars"></i></span>
              </button> <a class="navbar-brand" href="{% url 'interviewee:dashboard' %}">Interview - User</a>
              <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav ml-md-auto">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url 'interviewee:dashboard' %}" id="navbarDropdownMenuLink" data-toggle="dropdown">{{ user.first_name }}</a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="{% url 'logout' %}">logout</a>
                    </div>
                  </li>
                </ul>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </header>
    {% block intervieweecontent %}

    {% endblock %}
  {% else %}
    <p>Please login to see this page.</p>
  {% endif %}
{% endblock %}